name: Test
on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "README.md"
      - "LICENSE"
    tags-ignore:
      - "*"
env:
  GO_VERSION: "1.23.2"
  GOFLAGS: -buildvcs=false
  GOPROXY: https://proxy.golang.org,direct
jobs:
  lint:
    name: Run make lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Restore cached binaries
        id: cache-lint-restore
        uses: actions/cache/restore@v4
        with:
          path: bin/**
          key: ${{ runner.os }}-${{ hashFiles('Makefile') }}-lint
      - run: make lint
      - name: Save cached binaries
        if: steps.cache-lint-restore.outputs.cache-hit != 'true'
        id: cache-lint-save
        uses: actions/cache/save@v4
        with:
          path: bin/**
          key: ${{ steps.cache-lint-restore.outputs.cache-primary-key }}
  test:
    name: Run make test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make test
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
